[package]
name = "patata"
version = "0.0.1"
edition = "2018"
description = "patata"
license = "MIT"
authors = ["JAvier <javier.pedreira@intenthq.com"]

[dependencies]
git2 = "^0.8.0"

[dev-dependencies]
tempdir = "^0.3.5"